language: node_js
node_js:
  - "4"

# Handle git submodules myself
git:
  submodules: false

before_install:
  - echo $SSH_KEY > /home/travis/.ssh/id_rsa
  - chmod 0600 /home/travis/.ssh/id_rsa
  - echo $SSH_PUBLIC_KEY > /home/travis/.ssh/id_rsa.pub
  - chmod 0644 /home/travis/.ssh/id_rsa.pub
  - cat /home/travis/.ssh/id_rsa.pub
  - cat /home/travis/.ssh/id_rsa
  - cat /etc/ssh/sshd_config
  - sudo cp /home/travis/.ssh/id_rsa /root/.ssh/
  - sudo cp /home/travis/.ssh/id_rsa.pub /root/.ssh/
  - sudo chmod 0600 /root/.ssh/id_rsa
  - sudo chmod 0644 /root/.ssh/id_rsa.pub
  - sudo cat /root/.ssh/id_rsa
  - sudo eval "$(ssh-agent -s)"
  - sudo ssh-add /root/.ssh/id_rsa

install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # - git submodule update --init --recursive

  - npm install -g hexo-cli
  - npm install

before_script:
  - git config --global user.name 'xiewenda'
  - git config --global user.email 'xwd4java@163.com'

# command to run tests
script:
  - hexo generate

after_success:
  - hexo deploy
